### ISSUE TITLE
front-page.php template

### ISSUE THREAD

**Issue by fshequin** [fshequin/jwllc-starter#1]
I see that the slideshow is bolted into front-page.php but don't understand how it gets picked up by a page from the backend. I added home, news and then made news the posts feed and home page the static front page, but it's looking at base.php....I guess I need to figure out Roots template wrapper to get this understood. :-)

**Comment by jacksonwp** [comment]
You have it right. Should use front-page.php on the page set as home.

Follows standard template hierarchy.

Is this on your local install ?
--

Jackson Whelan (Mobile)
WordPress Web Design & Development

jacksonwhelan.com / jw@jacksonwhelan.com
On The Road / 802.483.4050

**Comment by fshequin** [comment]
Yes, this is on my local mamp setup and I commented out all the root relative url stuff......added the cpts.php file as an empty php file to clear that file not found error...then tried both a WP Gallery on the page called home and then I embedded the images in visual editor so they'd be attached images. Still no slideshow.....

**Comment by jacksonwp** [comment]
I must have screwed up the archive I sent

--

Jackson Whelan (Mobile)
WordPress Web Design & Development

jacksonwhelan.com / jw@jacksonwhelan.com
On The Road / 802.483.4050

**Comment by fshequin** [comment]
Half Time....woo hoooo :-)

**Comment by fshequin** [comment]
Mr. Shequine no Super Bowl comments in the code please.... :-(

**Comment by fshequin** [comment]
you can edit the code right here on Github, then I can pull the changes down to my install and boom it will work...... :-)

**Comment by jacksonwp** [comment]
cpts.php updated you should now see 'Slides' in your admin menu

**Comment by fshequin** [comment]
got it! wooo hooo......
